
name: "Determine Version"
description: "Determines the version of a build-in-progress by invoking GitVersion and saving an artifact of the result."
inputs:
  mode:
    description: "One of 'upload' or 'download'."
    required: true
  gitversion-version:
    description: "The version of GitVersion to use."
    required: true
    default: '6.1'
  versionjson-name:
    description: "The name of the JSON file containing the generated version information."
    required: true
    default: 'version.json'
  versionjson-path:
    description: "The path of the directory containing the JSON file of the generated version information."
    required: true
    default: './out'
  versionjson-artifact-name:
    description: "The name of the artifact which contains the JSON file of the generated version information."
    required: true
    default: 'version-json'
outputs:
  #
  # Commonplace GitVersion outputs.
  #
  AssemblySemFileVer:
    description: "AssemblySemFileVer"
    value: ${{ steps.gitversion_vars.outputs.AssemblySemFileVer }}
    # e.g. "0.3.16.0"
  AssemblySemVer:
    description: "AssemblySemVer"
    value: ${{ steps.gitversion_vars.outputs.AssemblySemVer }}
    # e.g. "0.3.16.0"
  BranchName:
    description: "BranchName"
    value: ${{ steps.gitversion_vars.outputs.BranchName }}
    # e.g. "20241215-dependency-updates-pt1"
  BuildMetaData:
    description: "BuildMetaData"
    value: ${{ steps.gitversion_vars.outputs.BuildMetaData }}
    # e.g. "7"
  CommitDate:
    description: "CommitDate"
    value: ${{ steps.gitversion_vars.outputs.CommitDate }}
    # e.g. "2024-01-09"
  CommitsSinceVersionSource:
    description: "CommitsSinceVersionSource"
    value: ${{ steps.gitversion_vars.outputs.CommitsSinceVersionSource }}
    # e.g. "7"
  EscapedBranchName:
    description: "EscapedBranchName"
    value: ${{ steps.gitversion_vars.outputs.EscapedBranchName }}
    # e.g. "20241215-dependency-updates-pt1"
  FullBuildMetaData:
    description: "FullBuildMetaData"
    value: ${{ steps.gitversion_vars.outputs.FullBuildMetaData }}
    # e.g. "7.Branch.20241215-dependency-updates-pt1.Sha.3614bd87c7c1b8d71473989432771cba257bcd00"
  FullSemVer:
    description: "FullSemVer"
    value: ${{ steps.gitversion_vars.outputs.FullSemVer }}
    # e.g. "0.3.16-20241215-dependency-updates-pt1.1+7"
  InformationalVersion:
    description: "InformationalVersion"
    value: ${{ steps.gitversion_vars.outputs.InformationalVersion }}
    # e.g. "0.3.16-20241215-dependency-updates-pt1.1+7.Branch.20241215-dependency-updates-pt1.Sha.3614bd87c7c1b8d71473989432771cba257bcd00"
  Major:
    description: "Major"
    value: ${{ steps.gitversion_vars.outputs.Major }}
    # e.g. "0"
  MajorMinorPatch:
    description: "MajorMinorPatch"
    value: ${{ steps.gitversion_vars.outputs.MajorMinorPatch }}
    # e.g. "0.3.16"
  Minor:
    description: "Minor"
    value: ${{ steps.gitversion_vars.outputs.Minor }}
    # e.g. "3"
  Patch:
    description: "Patch"
    value: ${{ steps.gitversion_vars.outputs.Patch }}
    # e.g. "16"
  PreReleaseLabel:
    description: "PreReleaseLabel"
    value: ${{ steps.gitversion_vars.outputs.PreReleaseLabel }}
    # TODO: "20241215-dependency-updates-pt1"
  PreReleaseLabelWithDash:
    description: "PreReleaseLabelWithDash"
    value: ${{ steps.gitversion_vars.outputs.PreReleaseLabelWithDash }}
    # TODO: "-20241215-dependency-updates-pt1"
  PreReleaseNumber:
    description: "PreReleaseNumber"
    value: ${{ steps.gitversion_vars.outputs.PreReleaseNumber }}
    # e.g. "1"
  PreReleaseTag:
    description: "PreReleaseTag"
    value: ${{ steps.gitversion_vars.outputs.PreReleaseTag }}
    # e.g. "20241215-dependency-updates-pt1.1"
  PreReleaseTagWithDash:
    description: "PreReleaseTagWithDash"
    value: ${{ steps.gitversion_vars.outputs.PreReleaseTagWithDash }}
    # e.g. "-20241215-dependency-updates-pt1.1"
  SemVer:
    description: "SemVer"
    value: ${{ steps.gitversion_vars.outputs.SemVer }}
    # e.g. "0.3.16-20241215-dependency-updates-pt1.1"
  Sha:
    description: "Sha"
    value: ${{ steps.gitversion_vars.outputs.Sha }}
    # e.g. "3614bd87c7c1b8d71473989432771cba257bcd00"
  ShortSha:
    description: "ShortSha"
    value: ${{ steps.gitversion_vars.outputs.ShortSha }}
    # e.g. "3614bd8"
  UncommittedChanges:
    description: "UncommittedChanges"
    value: ${{ steps.gitversion_vars.outputs.UncommittedChanges }}
    # e.g. "1"
  VersionSourceSha:
    description: "VersionSourceSha"
    value: ${{ steps.gitversion_vars.outputs.VersionSourceSha }}
    # TODO: "770b1b278a3c681d37436a15352009d3a7cee1d1"
  WeightedPreReleaseNumber:
    description: "WeightedPreReleaseNumber"
    value: ${{ steps.gitversion_vars.outputs.WeightedPreReleaseNumber }}
    # e.g. "1"
  #
  # We've attempted a backwards-compatible implementation of these remaining "GitVersion" outputs. Correctness TBD.
  #
  BuildMetaDataPadded:
    description: "BuildMetaDataPadded"
    value: ${{ steps.gitversion_vars.outputs.BuildMetaDataPadded }}
  LegacySemVer:
    description: "LegacySemVer"
    value: ${{ steps.gitversion_vars.outputs.LegacySemVer }}
  LegacySemVerPadded:
    description: "LegacySemVerPadded"
    value: ${{ steps.gitversion_vars.outputs.LegacySemVerPadded }}
  NuGetVersionV2:
    description: "NuGetVersionV2"
    value: ${{ steps.gitversion_vars.outputs.NuGetVersionV2 }}
  NuGetVersion:
    description: "NuGetVersion"
    value: ${{ steps.gitversion_vars.outputs.NuGetVersion }}
  NuGetPreReleaseTagV2:
    description: "NuGetPreReleaseTagV2"
    value: ${{ steps.gitversion_vars.outputs.NuGetPreReleaseTagV2 }}
  NuGetPreReleaseTag:
    description: "NuGetPreReleaseTag"
    value: ${{ steps.gitversion_vars.outputs.NuGetPreReleaseTag }}
  CommitsSinceVersionSourcePadded:
    description: "CommitsSinceVersionSourcePadded"
    value: ${{ steps.gitversion_vars.outputs.CommitsSinceVersionSourcePadded }}
  #
  # Miscellaneous helpful outputs.
  #
  versionjson-name:
    description: "The name of the JSON file containing the generated version information."
    value: ${{ inputs.versionjson-name }}
  versionjson-path:
    description: "The path of the directory containing the JSON file of the generated version information."
    value: ${{ inputs.versionjson-path }}
  versionjson-artifact-name:
    description: "The name of the artifact to which contains the JSON file of the generated version information."
    value: ${{ inputs.versionjson-artifact-name }}
  versionjson-filepath:
    description: "The path to the file containing the version information."
    value: ${{ steps.calculate_versionjson_filepath.outputs.filepath }}
runs:
  using: "composite"
  steps:
    - name: Cache dotnet tools
      if: inputs.mode == 'upload'
      id: cacher
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.HOME }}/.dotnet/tools
          ${{ env.USERPROFILE }}\\.dotnet\\tools
        key: ${{ runner.os }}-dotnet-tools-${{ hashFiles('**/global.json') }}
    - name: dotnet tool install -g GitVersion.Tool
      if: (steps.cacher.outputs.cache-hit != 'true') && (inputs.mode == 'upload')
      shell: pwsh
      run: dotnet tool install --global GitVersion.Tool --version ${{ inputs.gitversion-version }}
    - name: Check out repository full history
      if: inputs.mode == 'upload'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # GitVersion requires the full history to calculate the version.
    - name: Show GitVersion configuration
      if: inputs.mode == 'upload'
      shell: pwsh
      run: dotnet-gitversion /showconfig
    - name: Calculate file path
      id: calculate_versionjson_filepath
      shell: pwsh
      env:
        filename: "${{ inputs.versionjson-name }}"
        directory: "${{ inputs.versionjson-path }}"
      run: |
        [string] $filePath = Join-Path $Env:directory $Env:filename
        echo "::set-output name=filepath::$filePath"
    - name: Determine version
      if: inputs.mode == 'upload'
      id: generate_version_file
      shell: pwsh
      env:
        filePath: "${{ steps.calculate_versionjson_filepath.outputs.filepath }}"
      run: |
        New-Item (Split-Path $Env:filePath -Parent) -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
        dotnet-gitversion /output json | Out-File -FilePath $Env:filePath -Encoding UTF8
        [int] $gitversionExitCode = $LASTEXITCODE
        if ($gitversionExitCode -ne 0) {
          Write-Host "GitVersion failed. Re-running with diagnostic verbosity."
          dotnet-gitversion /output json /verbosity diagnostic
          exit $gitversionExitCode
        }
    - name: Elaborate version
      if: inputs.mode == 'upload'
      id: elaborate_version_file
      shell: pwsh
      env:
        filePath: "${{ steps.calculate_versionjson_filepath.outputs.filepath }}"
      run: |
        # Load the version information we just generated.
        $versionInfo = Get-Content -LiteralPath $Env:filePath -Encoding UTF8 | ConvertFrom-Json

        #
        # Backfill legacy outputs.
        #

        [string] $paddedNumberFormatPattern = "0000"

        [string] $BuildMetaDataPadded = $versionInfo.BuildMetaData -eq $null ? $null : ($versionInfo.BuildMetaData -as [int])?.ToString($paddedNumberFormatPattern)

        # TODO: Verify 'PreReleaseNumber' is correct suffix. Ambiguous from historical documentation found at https://github.com/GitTools/GitVersion/blob/v4.0.0/docs/more-info/variables.md.
        [Nullable[int]] $preReleaseNumber = $versionInfo.PreReleaseNumber -as [int]
        if ($preReleaseNumber -or $versionInfo.PreReleaseLabel) {
          [string] $NuGetPreReleaseTagV2 = $versionInfo.PreReleaseLabel + $preReleaseNumber.ToString($paddedNumberFormatPattern)
        } else {
          [string] $NuGetPreReleaseTagV2 = ""
        }
        # TODO: Determine correct provenance for 'NuGetPreReleaseTag'. Ambiguous from historical documentation found at https://github.com/GitTools/GitVersion/blob/v4.0.0/docs/more-info/variables.md.
        [string] $NuGetPreReleaseTag = $NuGetPreReleaseTagV2
        if ($preReleaseNumber -and $versionInfo.PreReleaseLabel) {
          [string] $LegacySemVer = $versionInfo.MajorMinorPatch + "-" + $versionInfo.PreReleaseLabel + $preReleaseNumber
          [string] $LegacySemVerPadded = $versionInfo.MajorMinorPatch + "-" + $versionInfo.PreReleaseLabel + $preReleaseNumber.ToString($paddedNumberFormatPattern)
        } else {
          [string] $LegacySemVer = $versionInfo.MajorMinorPatch
          [string] $LegacySemVerPadded = $versionInfo.MajorMinorPatch
        }
        # TODO: Determine correct provenance for 'NuGetVersion' and 'NuGetVersionV2'. Ambiguous from historical documentation found at https://github.com/GitTools/GitVersion/blob/v4.0.0/docs/more-info/variables.md.
        [string] $NuGetVersionV2 = $LegacySemVerPadded
        [string] $NuGetVersion = $LegacySemVerPadded

        [string] $CommitsSinceVersionSourcePadded = ($versionInfo.CommitsSinceVersionSource -as [int]).ToString($paddedNumberFormatPattern)

        $versionInfo | Add-Member -NotePropertyMembers @{
          'BuildMetaDataPadded'= $BuildMetaDataPadded;
          'LegacySemVer'= $LegacySemVer;
          'LegacySemVerPadded'= $LegacySemVerPadded;
          'NuGetVersionV2'= $NuGetVersionV2;
          'NuGetVersion'= $NuGetVersion;
          'NuGetPreReleaseTagV2'= $NuGetPreReleaseTagV2;
          'NuGetPreReleaseTag'= $NuGetPreReleaseTag;
          'CommitsSinceVersionSourcePadded'= $CommitsSinceVersionSourcePadded;
        }

        # Save the updated version information.
        $versionInfo | ConvertTo-Json | Out-File -FilePath $Env:filePath -Encoding UTF8 -Force
    - name: "Create artifact: ${{ inputs.versionjson-artifact-name }}"
      if: inputs.mode == 'upload'
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.versionjson-artifact-name }}"
        path: "${{ steps.calculate_versionjson_filepath.outputs.filepath }}"
        if-no-files-found: error
    - name: "Get artifact: ${{ inputs.versionjson-artifact-name }}"
      if: inputs.mode == 'download'
      uses: actions/download-artifact@v4
      with:
        name: "${{ inputs.versionjson-artifact-name }}"
        path: "${{ inputs.versionjson-path }}"
    - name: Populate version variables
      id: gitversion_vars
      shell: pwsh
      env:
        filePath: "${{ steps.calculate_versionjson_filepath.outputs.filepath }}"
      run: |
        [object] $version = Get-Content -Path $Env:filePath | ConvertFrom-Json
        foreach ($key in $version.PSObject.Properties.Name) {
          echo "::set-output name=$key::$($version.$key)"
        }
